### ISSUE TITLE
No requirements.txt file found in the repository.

### ISSUE THREAD

**Issue by lowtech81** [ds-kiel/LimitNet#1]
No requirements.txt file found in the repository.

**Comment by Alihjt** [comment]
> No requirements.txt file found in the repository.

Hi @lowtech81,

Thank you for bringing this to our attention.
We have added a requirements.txt file to the repository. This file includes all the necessary dependencies for the project.

If you encounter any further issues or have any questions, please feel free to reach out again.

**Comment by lowtech81** [comment]
It's my pleasure.
Thank you for sharing.
